[package]
name = "dynamic_fan_control"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "^0.9"
interp = { version = "1.0", features = ["interp_array"] }
lm-sensors = "*"
syslog = "*"
log = "*"
ipmiraw = "*"
