temperature_points:
  - name: "default"
    map:
      - temperature: 25
        fan_speed: 15
      - temperature: 45
        fan_speed: 25
      - temperature: 55
        fan_speed: 40
      - temperature: 70
        fan_speed: 65
setting:
  fan_num: 6
  interval: 300
  fan_map:
    - id: 0
      static_fan_map: 15
    - id: 1
      dynamic_cpu_chip: "coretemp-isa-0000"
      dynamic_fan_speed_map: "default"
    - id: 2
      static_fan_map: 15
    - id: 3
      static_fan_map: 15
    - id: 4
      dynamic_cpu_chip: "coretemp-isa-0001"
      dynamic_fan_speed_map: "default"
    - id: 5
      static_fan_map: 15
