temperature_points:
  - name: "default"
    map:
      - temperature: 25
        speed: 15
      - temperature: 45
        speed: 25
      - temperature: 55
        speed: 40
      - temperature: 70
        speed: 65
setting:
  fan_num: 6
  interval: 300
  device: dell
  fan_map:
    - id: 0
      static_speed_map: 15
    - id: 1
      dynamic_cpu_chip: "coretemp-isa-0000"
      dynamic_speed_map: "default"
    - id: 2
      static_speed_map: 15
    - id: 3
      static_speed_map: 15
    - id: 4
      dynamic_cpu_chip: "coretemp-isa-0001"
      dynamic_speed_map: "default"
    - id: 5
      static_speed_map: 15
